# Changes here will be overwritten by Copier;
_commit: 1b8f6fc
_src_path: gh:wtenbrink/copier-python-template
project_description: Demo project from the Copier Python Template
project_name: Copier Python Demo
